global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: fastify-app
    static_configs:
      - targets:
        - node:3000
  - job_name: node-scrapping
    static_configs:
      - targets:
        - node_exporter:9100
  - job_name: 'sqlite-scrapping'
    static_configs:
      - targets:
          - 'sqlite-exporter:9560'

rule_files:
  - rules.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
